ubsApp.advantageCardConfig={
    "advantageCardScenario":{
		"category":"advantageCard",
		"templates":[
			{
				"templateId":12,
				"templateType":"advantageCard",
                "advantageCardTitle":"{{advantageCardTitle}}",
                "background":"green",
                "color":"black",
                "reputationPointAvailableTitle":"{{reputationPointAvailableTitle}}",
                "conversionTitle":"{{conversionTitle}}",
                "numberToConvertTitle":"{{numberToConvertTitle}}",
                "numberOfAdvantageCardTitle":"{{numberOfAdvantageCardTitle}}",
                "checkTitle":"{{checkTitle}}",
                "numberOfAdvantageCardTitle":"{{numberOfAdvantageCardTitle}}",
                "reputationPointBalance":"{{reputationPointBalance}}",
                "cancelTitle":"{{cancelTitle}}",
                "convertTitle":"{{convertTitle}}"
			}
		]
	},
}