ubsApp.translation={
        "question1":"Looks like one customer wants to purchase items:<br>1.5kg Rice<br>2.5kg Dal<br>1 kg Atta<br><br> Cost of Rice/Dal/Atta per kg is 60/90/40 rupees respectively.<br> Can you tell how much money will you take from Customer?",
        "question2":"Looks like Same Customer is back.he wants to return few items and purchase soem new.<br>He wants to return<br>1kg Rice - Rs.60<br>1 kg of Dal- Rs 90<br><br> He wants to purchase <br>0.5 litre Oil<br> 6 chips packet<br> 1 ltr oil/1 chip packet cost Rs 90/10. <br> Can you tell how much money should Sardarji return to customer?",
        "question3":"Looks like Same Customer is back.He wants to return few items and purchase some new.<br>He wants to return<br>1kg Onion - Rs.19<br>1 kg of Potato- Rs 34<br><br> He wants to purchase <br>1.5kg Tomato<br> 1kg Cabbage<br>Per kg cost of tomato/cabbage is 26/24 rupees<br> Can you tell how much money should you pay?",
        "question4":"Looks like a Customer is back.he wants to return few items.<br>He wants to return<br>1kg Rice - Rs.60<br>1 kg of Dal - Rs 90<br><br> <br> Can you tell how much money will you return to customer?",
        "pratham_title_sales":"Sales",
        "pratham_title_surprise":"Surprise",
        "pratham_title_luck":"LUCK",
        "pratham_title_purchase":"Purchase",
        "pratham_title_start":"Start",
        "pratham_title_decision":"Decision Making",
        "close":"close",
        "scoreSideBar":"Score",
        "documentSideBar":"Document",
        "inventorySideBar":"Inventory",
        "meritSideBar":"Merit",
        "Rs": "₹",
        //This is where new addition started
        "inventoryTitle":"INVENTORY",
        "weekTitle":"WEEK",
        "lastBalanceTitle":"LAST BALANCE",
        "insuranceTitle":"INSURANCE",
        "inventoryValueTitle":"INVENTORY VALUE",
        "reputationTitle":"REPUTATION PTS",

    //This is where the new addition ended

        "enterPlayers":"Enter the number of Players",
        "initPageTitle":"Welcome to the Game",
        "storePlayerDetailsButton":"Next Page",
        "computerRequiredTitle":"Computer Required?",
        "playerNameTitle":"Player Name",
        "diceValueTitle":"Dice Value",

        "easy":"Easy",
        "medium":"Medium",
        "hard":"Hard",
        "name":"Name",

        "bankBalanceTitle":"BANK BALANCE",
        "debtTitle":"DEBT",
        "cashTitle":"CASH",
        "creditTitle":"CREDIT",
        "creditLimitTitle":"CREDIT LIMIT",
        "nextQuestion":"Next Question!",
        
        "q1-correct":"Yay, you answered correct. Your balance increases.",
        "q1-wrong":">Oops!! you answered incorrect. You lost money.",
        "q1-vvwrong":">Oops!! you answered incorrect. You lost money.",

        "q2-correct":"Yay, you answered correct. Your balance increases.",
        "q2-wrong":"Oops!! you answered incorrect. You lost money.",
        "q2-vvwrong":"Oops!! you answered incorrect. You lost money.",

        "q3-correct":"Yay, you answered correct. Your balance increases.",
        "q3-wrong":"Oops!! you answered incorrect. You lost money.",
        "q3-vvwrong":"Oops!! you answered incorrect. You lost money.",

        "q4-correct":"Yay, you answered correct. Your balance increases.",
        "q4-wrong":"Oops!! you answered incorrect. You lost money.",
        "q4-vvwrong":"Oops!! you answered incorrect. You lost money.",
        "paymentQuestion1":"You have been fined for not having driving license.",
        "paymentQuestion2":"You have been fined Rs.1000 for not having shop License.",
        "luckQuestion1":"You have gained Rs. 1000 for paying income tax.",
        "luckQuestion2":"You have lost Rs. 1000 for not paying income tax.",
        
        //new
        "validAmount":"PLEASE ENTER A VALID AMOUNT",
        "lessMoney":"YOU HAVE ENTERED LESS MONEY",
        "moreMoney":"YOU HAVE ENTERED MORE MONEY",
        "moreCash":"YOU HAVE ENTERED MORE CASH THAN YOU HAVE",
        "bankBalance":"YOU HAVE INSUFFICIENT BANK BALANCE",
        "lotDebt":"YOU HAVE A LOT OF DEBT",
        "pleaseConfirm":"PLEASE CONFIRM THE AMOUNT YOU WANT",
        "noDebt":"YOU DON'T HAVE ANY DEBTS.",


        "itemRateDisplay":{

            "Wheat":"₹ 50/kg",
            "Rice":"₹ 110/kg",
            "Dal":"₹ 80/kg",
            "Sugar":"₹ 50/kg",
            "Milk":"₹ 45/litre",
            "Oil":"₹ 125/litre",
            "Rope":"₹ 35/10 m",
            "Chocolate":"₹ 40/chocolate",
            "Eggs":"₹ 5.5/egg",
            "Biscuits":"₹ 25/packet",
            "Soap":"₹ 27/soap",
            "Shampoo":"₹ 45/100ml",
            "Detergent":"₹ 37/500gm"
        },

        "payDebtTitle":"PAY DEBT",
        "transferToBank":"TRANSFER CASH TO BANK",
        "payment":"PAYMENT",
        "youCan":"YOU CAN",
        "alternateMessage":"OR TO WAIVE FINE YOU CAN ",
        "transferTitle":"TRANSFER",
        "payOffTitle":"PAY OFF",
        "payDebtTitle":"PAY DEBT",
        "payTitle":"PAY",
        "transferToBankTitle":"TRANSFER CASH TO BANK",
        "debtAmountTitle":"Debt Amount",
        "cancelTitle":"CANCEL",

        "amountToPayTitle":"AMOUNT TO PAY",
        "amountToTransferTitle":"AMOUNT TO TRANSFER",
        "modeOfPaymentTitle":"MODE OF PAYMENT",
        "helpTitle":"HELP",
        "gainTitle":"GAIN",
        "takeQuizTitle":"TAKE A QUIZ",
        "checkWildCard":"CHECK WILD CARD",
        "current":"CURRENT",
        "level":"LEVEL",
        "confirmTitle":"CONFIRM",
        "newInventoryLevelTitle":"NEW INVENTORY LEVEL",
        "costTitle":"COST",
        "amountTitle":"AMOUNT",
        "payByTitle":"PAY BY",
        "addModeTitle":"ADD MODE",
        "doneTitle":"DONE",
        "noThanksTitle":"NO THANKS",
        "or":"OR",
        "cheque":"CHEQUE",

        //Sales

        "receiptHeading":"Super Market Receipt",
        "receiptGen":"Receipt Generation",
        "Order":"Order",
        "Customer":"Customer",
        "Items":"Items",
        "Quantity":"Quantity",
        "Rate":"Rate",
        "Amount":"Amount",
        "Tools":"Tools",
        "Wheat":"Wheat",
        "Rice":"Rice",
        "Dal":"Dal",
        "Sugar":"Sugar",
        "Milk":"Milk",
        "Oil":"Oil",
        "Rope":"Rope",
        "Chocolate":"Chocolate",
        "Eggs":"Eggs",
        "Biscuits":"Biscuits",
        "Soap":"Soap",
        "Shampoo":"Shampoo",
        "Detergent":"Detergent",

        //Decision
        "invVal":"INVENTORY VALUE",
        "repPoints":"REPUTATION POINTS",
        "Decision":"Decision",


    }