ubsApp.translation={
        "question1":"Looks like one customer wants to purchase items:<br>1.5kg Rice<br>2.5kg Dal<br>1 kg Atta<br><br> Cost of Rice/Dal/Atta per kg is 60/90/40 rupees respectively.<br> Can you tell how much money will you take from Customer?",
        "question2":"Looks like Same Customer is back.he wants to return few items and purchase soem new.<br>He wants to return<br>1kg Rice - Rs.60<br>1 kg of Dal- Rs 90<br><br> He wants to purchase <br>0.5 litre Oil<br> 6 chips packet<br> 1 ltr oil/1 chip packet cost Rs 90/10. <br> Can you tell how much money should Sardarji return to customer?",
        "question3":"Looks like Same Customer is back.He wants to return few items and purchase some new.<br>He wants to return<br>1kg Onion - Rs.19<br>1 kg of Potato- Rs 34<br><br> He wants to purchase <br>1.5kg Tomato<br> 1kg Cabbage<br>Per kg cost of tomato/cabbage is 26/24 rupees<br> Can you tell how much money should you pay?",
        "question4":"Looks like a Customer is back.he wants to return few items.<br>He wants to return<br>1kg Rice - Rs.60<br>1 kg of Dal - Rs 90<br><br> <br> Can you tell how much money will you return to customer?",
        "pratham_title_sales":"Sales",
        "pratham_title_surprise":"Surprise",
        "pratham_title_luck":"LUCK",
        "pratham_title_purchase":"Purchase",
        "pratham_title_start":"Start",
        "pratham_title_decision":"Decision Making",
        "close":"close",
        "scoreSideBar":"Score",
        "documentSideBar":"Document",
        "inventorySideBar":"Inventory",
        "meritSideBar":"Merit",
        "Rs": "₹",
        //This is where new addition started
        "inventoryTitle":"INVENTORY",
        "weekTitle":"WEEK",
        "lastBalanceTitle":"LAST BALANCE",
        "insuranceTitle":"INSURANCE",
        "inventoryValueTitle":"INVENTORY VALUE",
        "reputationTitle":"REPUTATION PTS",

    //This is where the new addition ended

        "enterPlayers":"Enter the number of Players",
        "initPageTitle":"Welcome to the Game",
        "storePlayerDetailsButton":"Next Page",
        "computerRequiredTitle":"Computer Required?",
        "playerNameTitle":"Player Name",
        "diceValueTitle":"Dice Value",

        "easy":"Easy",
        "medium":"Medium",
        "hard":"Hard",
        "name":"Name",

        "bankBalanceTitle":"BANK BALANCE",
        "debtTitle":"DEBT",
        "cashTitle":"CASH",
        "creditTitle":"CREDIT",
        "creditLimitTitle":"CREDIT LIMIT",
        "nextQuestion":"Next Question!",
        
        "q1-correct":"Yay, you answered correct. Your balance increases.",
        "q1-wrong":">Oops!! you answered incorrect. You lost money.",
        "q1-vvwrong":">Oops!! you answered incorrect. You lost money.",

        "q2-correct":"Yay, you answered correct. Your balance increases.",
        "q2-wrong":"Oops!! you answered incorrect. You lost money.",
        "q2-vvwrong":"Oops!! you answered incorrect. You lost money.",

        "q3-correct":"Yay, you answered correct. Your balance increases.",
        "q3-wrong":"Oops!! you answered incorrect. You lost money.",
        "q3-vvwrong":"Oops!! you answered incorrect. You lost money.",

        "q4-correct":"Yay, you answered correct. Your balance increases.",
        "q4-wrong":"Oops!! you answered incorrect. You lost money.",
        "q4-vvwrong":"Oops!! you answered incorrect. You lost money.",
        "paymentQuestion1":"You have been fined for not having driving license.",
        "paymentQuestion2":"You have been fined Rs.1000 for not having shop License.",
        "luckQuestion1":"You have gained Rs. 1000 for paying income tax.",
        "luckQuestion2":"You have lost Rs. 1000 for not paying income tax.",
        
        //new
        "validAmount":"PLEASE ENTER A VALID AMOUNT",
        "lessMoney":"YOU HAVE ENTERED LESS MONEY",
        "moreMoney":"YOU HAVE ENTERED MORE MONEY",
        "moreCash":"YOU HAVE ENTERED MORE CASH THAN YOU HAVE",
        "bankBalance":"YOU HAVE INSUFFICIENT BANK BALANCE",
        "lotDebt":"YOU HAVE A LOT OF DEBT",
        "pleaseConfirm":"PLEASE CONFIRM THE AMOUNT YOU WANT",
        "noDebt":"YOU DON'T HAVE ANY DEBTS.",


        "itemRateDisplay":{

            "1":"₹ 50/kg",
            "2":"₹ 110/kg",
            "3":"₹ 80/kg",
            "4":"₹ 50/kg",
            "5":"₹ 45/litre",
            "6":"₹ 125/litre",
            "7":"₹ 35/10 m",
            "8":"₹ 40/chocolate",
            "9":"₹ 5.5/egg",
            "10":"₹ 25/packet",
            "11":"₹ 27/soap",
            "12":"₹ 45/100ml",
            "13":"₹ 37/500gm"
        },

        "payDebtTitle":"PAY DEBT",
        "transferToBank":"TRANSFER CASH TO BANK",
        "payment":"PAYMENT",
        "youCan":"YOU CAN",
        "alternateMessage":"OR TO WAIVE FINE YOU CAN ",
        "transferTitle":"TRANSFER",
        "payOffTitle":"PAY OFF",
        "payDebtTitle":"PAY DEBT",
        "payTitle":"PAY",
        "transferToBankTitle":"TRANSFER CASH TO BANK",
        "debtAmountTitle":"Debt Amount",
        "cancelTitle":"CANCEL",

        "amountToPayTitle":"AMOUNT TO PAY",
        "amountToTransferTitle":"AMOUNT TO TRANSFER",
        "modeOfPaymentTitle":"MODE OF PAYMENT",
        "helpTitle":"HELP",
        "gainTitle":"GAIN",
        "takeQuizTitle":"TAKE A QUIZ",
        "checkWildCard":"CHECK WILD CARD",
        "current":"CURRENT",
        "level":"LEVEL",
        "confirmTitle":"CONFIRM",
        "newInventoryLevelTitle":"NEW INVENTORY LEVEL",
        "costTitle":"COST",
        "amountTitle":"AMOUNT",
        "payByTitle":"PAY BY",
        "addModeTitle":"ADD MODE",
        "doneTitle":"DONE",
        "noThanksTitle":"NO THANKS",
        "or":"OR",
        "cheque":"CHEQUE",

        //Sales

        "receiptHeading":"Super Market Receipt",
        "receiptGen":"Receipt Generation",
        "Order":"Order",
        "Customer":"Customer",
        "Items":"Items",
        "Quantity":"Quantity",
        "Rate":"Rate",
        "Amount":"Amount",
        "Tools":"Tools",
        "Wheat":"Wheat",
        "Rice":"Rice",
        "Dal":"Dal",
        "Sugar":"Sugar",
        "Milk":"Milk",
        "Oil":"Oil",
        "Rope":"Rope",
        "Chocolate":"Chocolate",
        "Eggs":"Eggs",
        "Biscuits":"Biscuits",
        "Soap":"Soap",
        "Shampoo":"Shampoo",
        "Detergent":"Detergent",

        //Decision
        "invVal":"INVENTORY VALUE",
        "repPoints":"REPUTATION POINTS",
        "Decision":"Decision",
        "questionDecisionInsurance":"An Insurance Advisor is offering you comprehensive shop insurance that covers fire, theft and  natural disasters.<br><br>Premium: Between Rs.15000 and Rs. 24,000 anuallly based on cover SumAssured: Between 3,00,000 and 5,00,000<br><br>Would you like to buy insurance?",
        "yes":"YES",
        "no":"NO",

        "decisionQ1":"Food inspector visits your shop and it is found that you have some products that are expired but still kept for sale.<br>Food inspector raises objection. He asks for shop documents. You don't have all documents.<br>",
        "decisionQ2":"Last year during extremely heavy rains, there was immense flooding and water logging in your area which led to partial or complete damage of the food items in your shop. <br> of the neighbouring shops were also affected. Your insurance agent has come for purchase of your policy? Premium cost will between Rs 3000 - Rs 6800 per year. <br>Will you purchase it ?",
        "decisionQ3":"You need funds to repair the broken ceiling in your store. The cost to repair the ceiling is Rs. 10000. Would you - ",
        "decisionQ4":"You decide not to pay taxes at all in spite of having a significant income. <br>Income tax officer has sent you a notice for payment of Rs.20000 and fine of Rs.3500.",
        "decisionQ5":"A customer purchases goods worth 1200. He gives you a ₹ 2000 note. You return 700 rupees. The customer doesn't count the money and leaves. Later you realize that you didn't return 100 rupees. Will you return 100 rupees to customer when they visit your shop again.",
        "decisionQ6":"You need to buy a weighing machine. The electronic machine works on electricity but can also be battery operated. It will cost Rs. 1200. It measures accurate quantities of products.  A Conventional one will cost you Rs. 500 Which one will you buy?",
        "decisionQ7":"You heard about security camera that will continuously monitor and record the activities in shop. It will cost you Rs. 5000. Will you install it.",
        "decisionQ8":"A sales man came to your shop and said that there is an offer going on where if you buy 20 kg of washing powder worth Rs 1000, you will get Rs 500 cash back. The washing powder was nonbranded and not packaged properly. Will you buy it?",
        "decisionQ9":"Your uncle in village is ill and alone. Will you go to look after him? Shut shop for 7 days. Lose profit of 7,000 but gain 20 merit points.",
        "decisionQ10":"Will you give discount on packet of chips to sale off the existing stock which is expired. You will get a profit 500 Rs if you sell them.",
        "decisionQ11":"Your delivery van was stopped for breaking the signal ,You are late for a big order. What would you do.",
        "decisionQ12":"You have refrigerator in your shop. It needs servicing. One service costs Rs. 750. A service man gives you an offer where you will get one service free when you pay advance money for 3 regular service. ",
        "decisionQ13":"Since, there are voltage fluctuations in your area. You purchased voltage stablizer to safeguard refrigerator, electric weighing balace. It cost you Rs. 3000. This will save you from damaging stock worth Rs. 700 in this week and more in the future. Will you purchase it?",
        "decisionQ14":"3 new grocery shops have opened in the 5 km vicinity. <br>To make your store known, you can send out pamphlets that will cost you Rs. 1000 to print and distribute. This could result in sales increase between Rs. 500 - 3000. <br>Will you do it?",
        "decisionQ15":"The shop also sells SIM cards. A customer offers you Rs. 2000 to sell him a SIM card without KYC documents. Do you accept?",


        "decisionQ1O1":"Do you bribe the inspector Rs. 1000? ",
        "decisionQ1O2":"Do you pay the fine Rs. 1500 and documentation fees of Rs. 1000?",

        "decisionQ3O1":"avail of a loan from Punjab National Bank?",
        "decisionQ3O2":"take money from friend?",
        "decisionQ3O3":"take money from an unauthorised dealer?",

        "decisionQ4O1":"Would you pay the tax and fine?",
        "decisionQ4O2":"would you ignore it.",
        "decisionQ4O3":"would you bribe the tax officer of Rs 5000?",

        "decisionQ6O1":"Electronic Machine",
        "decisionQ6O2":"Conventional Machine",
        

        "decisionQ11O1":"Do you bribe the police Rs 100 and rush for delivery. ",
        "decisionQ11O2":"Pay the fine of Rs 500 by going to the police station and get late for the delivery",

            //Insurance

        "insuranceType":"Select Insurance Type(s):",
        "Insurance":"Insurance",
        "insurance1":"Theft",
        "insurance2":"Accident",
        "insurance3":"Natural Calamities",
        "premium":"Annual Premium :",
        "sumAssured":"Sum Assured:",
        "buy":"Buy",
        "cancel":"Cancel",
        "cashTitleName":"CASH",
        "chequeTitleName":"CHEQUE",
        "mode":"Mode of Payment :",
    }