ubsApp.centerScoreBoardConfig={
    "centerScoreBoard":{
    "templates":[
        {
            "templateId":13,
            "templateType":"centerScoreBoard",
            "bankBalanceTitle":"{{bankBalanceTitle}}",
            "cashTitle":"{{cashTitle}}",
            "debtTitle":"{{debtTitle}}",
            "withdrawTitle":"{{withdrawTitle}}",
            "transferTitle":"{{transferTitle}}",
            "payOffTitle":"{{payOffTitle}}",
            "playerNameLabel":"{{playerNameTitle}}",
            "diceValueLabel":"{{diceValueTitle}}",
        }
    ]
}
}